version: "3.7"

services:
  nginx:
    build: nginx
    image: staticfloat/nginx-certbot:latest
    environment:
      CERTBOT_EMAIL: jungche_hong@xv-global.com
    volumes:
        - letsencrypt:/etc/letsencrypt
    network_mode: "host"

volumes:
  letsencrypt: {}


